#!/usr/bin/env python3
"""
Bahria University LMS Assignment Watcher
=========================================
Automatically checks the LMS for new assignments every hour,
downloads them, and sends push notifications via ntfy.sh.

Author: Generated by Antigravity
"""

import asyncio
import json
import logging
import os
import re
import sys
import time
from datetime import datetime
from pathlib import Path
from urllib.parse import urljoin, urlparse

import httpx
from playwright.async_api import async_playwright, TimeoutError as PlaywrightTimeout

# ─────────────────────────────────────────────
#  USER CONFIGURATION  ← Edit these, OR set as environment variables
# ─────────────────────────────────────────────

# Environment variables take priority (used by GitHub Actions secrets)
LMS_USERNAME   = os.environ.get("LMS_USERNAME",   "01-136242-029")
LMS_PASSWORD   = os.environ.get("LMS_PASSWORD",   "123asd90@90#90")
NTFY_TOPIC     = os.environ.get("NTFY_TOPIC",     "bahria-assignments-uzair")
CAMPUS_NAME    = os.environ.get("CAMPUS_NAME",    "Islamabad E-8 Campus")

# ─────────────────────────────────────────────
#  PATHS  (auto-detected; change only if needed)
# ─────────────────────────────────────────────

# On GitHub Actions: save files inside the workspace so they can be
# uploaded as artifacts. Locally: save to ~/Downloads/BahriaAssignments.
_IN_GH_ACTIONS = bool(os.environ.get("GITHUB_ACTIONS"))

if _IN_GH_ACTIONS:
    DOWNLOAD_DIR = Path(os.environ.get("GITHUB_WORKSPACE", ".")) / "downloads"
else:
    DOWNLOAD_DIR = Path.home() / "Downloads" / "BahriaAssignments"

LOG_FILE   = Path.home() / "bahria_watcher.log"
STATE_FILE = Path.home() / ".bahria_downloaded.json"

# GitHub Actions run URL — included in notifications so you can click
# straight to the artifact download page.
_GH_RUN_URL = ""
if _IN_GH_ACTIONS:
    _server = os.environ.get("GITHUB_SERVER_URL", "https://github.com")
    _repo   = os.environ.get("GITHUB_REPOSITORY", "")
    _run_id = os.environ.get("GITHUB_RUN_ID", "")
    if _repo and _run_id:
        _GH_RUN_URL = f"{_server}/{_repo}/actions/runs/{_run_id}"

# ─────────────────────────────────────────────
#  URLS & CONSTANTS
# ─────────────────────────────────────────────

LMS_URL        = "https://lms.bahria.edu.pk"
NTFY_URL       = f"https://ntfy.sh/{NTFY_TOPIC}"

DOWNLOADABLE_EXTENSIONS = {".pdf", ".docx", ".doc", ".zip", ".pptx",
                            ".ppt", ".xlsx", ".xls", ".rar", ".7z", ".txt"}

# ─────────────────────────────────────────────
#  LOGGING SETUP
# ─────────────────────────────────────────────

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  [%(levelname)s]  %(message)s",
    handlers=[
        logging.FileHandler(LOG_FILE, encoding="utf-8"),
        logging.StreamHandler(sys.stdout),
    ],
)
log = logging.getLogger("bahria_watcher")


# ─────────────────────────────────────────────
#  STATE MANAGEMENT
# ─────────────────────────────────────────────

def load_state() -> dict:
    """Load already-downloaded assignments from JSON file."""
    if STATE_FILE.exists():
        try:
            with open(STATE_FILE, "r", encoding="utf-8") as f:
                return json.load(f)
        except (json.JSONDecodeError, IOError):
            log.warning("Could not read state file; starting fresh.")
    return {}


def save_state(state: dict) -> None:
    """Persist the downloaded-assignments state."""
    with open(STATE_FILE, "w", encoding="utf-8") as f:
        json.dump(state, f, indent=2)


# ─────────────────────────────────────────────
#  NOTIFICATIONS
# ─────────────────────────────────────────────

def send_notification(title: str, message: str, priority: str = "default") -> None:
    """Send a push notification via ntfy.sh."""
    try:
        resp = httpx.post(
            NTFY_URL,
            content=message.encode("utf-8"),
            headers={
                "Title": title,
                "Priority": priority,
                "Tags": "books,bahria",
                "Content-Type": "text/plain; charset=utf-8",
            },
            timeout=10,
        )
        resp.raise_for_status()
        log.info(f"Notification sent: {title}")
    except Exception as e:
        log.error(f"Failed to send notification: {e}")


# ─────────────────────────────────────────────
#  FILE DOWNLOAD
# ─────────────────────────────────────────────

def sanitize_filename(name: str) -> str:
    """Remove characters that are invalid in file/directory names."""
    return re.sub(r'[\\/*?:"<>|]', "_", name).strip()


def download_file(url: str, dest_path: Path, cookies: dict) -> bool:
    """Download a single file using httpx and the current session cookies."""
    try:
        dest_path.parent.mkdir(parents=True, exist_ok=True)
        with httpx.stream("GET", url, cookies=cookies, follow_redirects=True,
                          timeout=60) as resp:
            resp.raise_for_status()
            with open(dest_path, "wb") as f:
                for chunk in resp.iter_bytes(chunk_size=8192):
                    f.write(chunk)
        log.info(f"Downloaded → {dest_path}")
        return True
    except Exception as e:
        log.error(f"Download failed for {url}: {e}")
        return False


# ─────────────────────────────────────────────
#  MAIN BROWSER AUTOMATION
# ─────────────────────────────────────────────

async def run_watcher() -> None:
    """Full automation flow: login → navigate → scrape → download → notify."""
    state = load_state()
    new_assignments: list[dict] = []

    async with async_playwright() as pw:
        browser = await pw.chromium.launch(
            headless=True,
            args=["--no-sandbox", "--disable-dev-shm-usage"],
        )
        context = await browser.new_context(
            viewport={"width": 1280, "height": 800},
            user_agent=(
                "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/120.0.0.0 Safari/537.36"
            ),
        )
        page = await context.new_page()

        try:
            # ── Step 1: Open LMS portal landing page ─────────────────────
            log.info("Navigating to LMS portal …")
            await page.goto(LMS_URL, wait_until="networkidle", timeout=60_000)

            # ── Step 2: Click 'Student Sign In' on the landing page ───────
            log.info("Clicking Student Sign In …")
            student_signin_selectors = [
                "#BodyPH_hlStudent",
                "a:has-text('Student Sign In')",
                "a:has-text('Student')",
            ]
            for sel in student_signin_selectors:
                try:
                    btn = page.locator(sel).first
                    if await btn.is_visible(timeout=5_000):
                        await btn.click()
                        await page.wait_for_load_state("networkidle", timeout=30_000)
                        log.info(f"Clicked Student Sign In via: {sel}")
                        break
                except Exception:
                    continue

            log.info(f"Login form URL: {page.url}")

            # ── Step 3: Select campus/institute (on login page) ───────────
            log.info(f"Selecting campus: {CAMPUS_NAME} …")
            campus_selectors = [
                "#BodyPH_ddlInstituteID",
                "select[id*='Institute']",
                "select[id*='Campus']",
            ]
            campus_selected = False
            for sel in campus_selectors:
                try:
                    dropdown = page.locator(sel).first
                    if await dropdown.is_visible(timeout=5_000):
                        # Try by value first (value=1 = Islamabad E-8)
                        try:
                            await dropdown.select_option(value="1")
                            log.info(f"Campus selected by value='1' via {sel}")
                            campus_selected = True
                            break
                        except Exception:
                            pass
                        # Try by label (exact then partial)
                        try:
                            await dropdown.select_option(label=CAMPUS_NAME)
                            campus_selected = True
                        except Exception:
                            options = await dropdown.evaluate(
                                "el => Array.from(el.options).map(o => o.text)"
                            )
                            match = next(
                                (o for o in options
                                 if CAMPUS_NAME.lower() in o.lower()), None
                            )
                            if match:
                                await dropdown.select_option(label=match)
                                campus_selected = True
                            else:
                                log.warning(f"Campus '{CAMPUS_NAME}' not found in: {options}")
                                continue
                        await page.wait_for_load_state("networkidle", timeout=10_000)
                        log.info(f"Campus selected via {sel}")
                        break
                except Exception as ex:
                    log.debug(f"Campus selector {sel} failed: {ex}")
                    continue

            if not campus_selected:
                log.warning("Could not select campus; continuing with default …")

            # ── Step 4: Fill credentials ──────────────────────────────────
            log.info("Filling login credentials …")
            enrollment_selectors = [
                "#BodyPH_tbEnrollment",
                "input[id*='Enrollment']",
                "input[id*='enrollment']",
                "input[id*='username']",
                "input[id*='Username']",
                "input[name='username']",
                "input[type='text']:visible",
            ]
            filled_user = False
            for sel in enrollment_selectors:
                try:
                    field = page.locator(sel).first
                    if await field.is_visible(timeout=3_000):
                        await field.fill(LMS_USERNAME)
                        filled_user = True
                        log.info(f"Username filled via {sel}")
                        break
                except Exception:
                    continue

            if not filled_user:
                raise Exception("Could not find username/enrollment input field on login page.")

            password_selectors = [
                "#BodyPH_tbPassword",
                "input[id*='Password']",
                "input[id*='password']",
                "input[type='password']",
            ]
            for sel in password_selectors:
                try:
                    field = page.locator(sel).first
                    if await field.is_visible(timeout=3_000):
                        await field.fill(LMS_PASSWORD)
                        log.info(f"Password filled via {sel}")
                        break
                except Exception:
                    continue

            # ── Step 5: Click login button & wait for redirect ────────────
            log.info("Clicking login button …")
            login_btn_selectors = [
                "#BodyPH_btnLogin",
                "input[id*='btnLogin']",
                "button[type='submit']",
                "input[type='submit']",
                "input[value='Sign In']",
                "input[value='Login']",
            ]
            login_url_before = page.url
            for sel in login_btn_selectors:
                try:
                    btn = page.locator(sel).first
                    if await btn.is_visible(timeout=3_000):
                        await btn.click()
                        log.info(f"Login button clicked via: {sel}")
                        break
                except Exception:
                    continue

            # Wait up to 15 s for the URL to change (successful login redirects away)
            try:
                await page.wait_for_url(
                    lambda url: url != login_url_before,
                    timeout=15_000,
                )
            except PlaywrightTimeout:
                # URL didn't change; check for an error message on the page
                page_text = await page.inner_text("body")
                if any(kw in page_text.lower() for kw in
                       ["invalid", "incorrect", "wrong", "error", "failed"]):
                    raise Exception(
                        "Login failed — credentials appear to be incorrect. "
                        "Please check LMS_USERNAME and LMS_PASSWORD."
                    )
                # No error shown either — wait a bit more for slow network
                await page.wait_for_load_state("networkidle", timeout=20_000)

            log.info(f"Post-login URL: {page.url}")

            # ── Step 6: Navigate to LMS (opens in new tab) ────────────────
            log.info("Looking for LMS navigation button …")
            lms_button_selectors = [
                "a:has-text('LMS')",
                "button:has-text('LMS')",
                "a:has-text('Go to LMS')",
                "a[href*='lms.bahria']",
                "a[href*='/LMS']",
                "input[value*='LMS']",
                "button:has-text('Proceed')",
            ]
            lms_page = None
            for sel in lms_button_selectors:
                try:
                    btn = page.locator(sel).first
                    if not await btn.is_visible(timeout=4_000):
                        continue
                    # LMS link usually opens target=_blank; capture the new page
                    async with context.expect_page(timeout=10_000) as new_page_event:
                        await btn.click()
                    lms_page = await new_page_event.value
                    await lms_page.wait_for_load_state("networkidle", timeout=30_000)
                    log.info(f"LMS opened in new tab: {lms_page.url}")
                    page = lms_page
                    break
                except PlaywrightTimeout:
                    # No new tab opened; check if same-tab navigation happened
                    await page.wait_for_load_state("networkidle", timeout=10_000)
                    if "login" not in page.url.lower():
                        log.info(f"LMS same-tab navigation to: {page.url}")
                        break
                    log.debug(f"Selector '{sel}' did not navigate away.")
                    continue
                except Exception as ex:
                    log.debug(f"LMS selector '{sel}' failed: {ex}")
                    continue

            if lms_page is None:
                # Fallback: all new tabs opened without us catching them
                all_pages = context.pages
                if len(all_pages) > 1:
                    page = all_pages[-1]
                    await page.wait_for_load_state("networkidle", timeout=20_000)
                    log.info(f"Switched to last tab: {page.url}")

            log.info(f"Now on LMS: {page.url}")

            # ── Step 5: Navigate to Assignments ──────────────────────────
            log.info("Looking for Assignments in sidebar …")
            assignment_selectors = [
                "a:has-text('Assignments')",
                "li:has-text('Assignments') a",
                "a[href*='assignment']",
                "a[href*='Assignment']",
                "span:has-text('Assignments')",
            ]
            for sel in assignment_selectors:
                try:
                    locator = page.locator(sel).first
                    if await locator.is_visible(timeout=5_000):
                        await locator.click()
                        await page.wait_for_load_state("networkidle", timeout=30_000)
                        log.info(f"Clicked Assignments via: {sel}")
                        break
                except Exception:
                    continue

            log.info(f"Assignments page URL: {page.url}")

            # ── Step 6: Iterate courses → scrape per-course assignments ───
            # The page shows "Please select a course" by default.
            # Selecting #courseId triggers an AJAX update with the table.
            # Download links look like:  Download.php?k=<base64>
            log.info("Reading course list from #courseId dropdown …")
            base_url = f"{urlparse(page.url).scheme}://{urlparse(page.url).netloc}"

            course_options = await page.evaluate("""
                () => {
                    const sel = document.querySelector('#courseId');
                    if (!sel) return [];
                    return Array.from(sel.options)
                        .filter(o => o.value && o.value.trim() !== '')
                        .map(o => ({ value: o.value, text: o.text.trim() }));
                }
            """)

            if not course_options:
                log.warning("No courses found in #courseId dropdown; "
                            "falling back to full-page link scan.")
                course_options = []

            log.info(f"Found {len(course_options)} course(s) to check.")
            downloadable = []          # { url, title, deadline, course_name }

            async def _scrape_unsubmitted(course_name: str) -> list:
                """
                Scan the assignment table for THIS course and return only
                the professor's question-file links for assignments that the
                student has NOT yet submitted.

                Table column layout (0-indexed):
                  0  Assign No.
                  1  Title
                  2  Assignment file  ← what we want to download
                  3  Added Submission ← student's own upload — SKIP
                  4  Marks Obtained
                  5  Returned Submission (Comments)
                  6  Action           ← "Submit" button = not yet submitted
                  7  Deadline
                """
                await page.wait_for_load_state("networkidle", timeout=15_000)
                await page.wait_for_timeout(1_500)   # let AJAX fully paint

                results = await page.evaluate("""
                    () => {
                        const out = [];
                        const rows = document.querySelectorAll('table tbody tr');

                        rows.forEach(row => {
                            const cells = row.querySelectorAll('td');
                            if (cells.length < 7) return;   // malformed row

                            // ── Check Action cell (col 6) for a Submit button ──
                            const actionCell = cells[6];
                            const actionText = actionCell.innerText.trim().toLowerCase();
                            const hasSubmitBtn = (
                                actionCell.querySelector('a, button, input[type="submit"]') !== null &&
                                (actionText.includes('submit') || actionText.includes('upload'))
                            );
                            if (!hasSubmitBtn) return;   // already submitted or no action

                            // ── Grab the assignment file link (col 2) ──
                            const assignCell = cells[2];
                            const link = assignCell.querySelector('a[href*="Download.php"]') ||
                                         assignCell.querySelector('a[href]');
                            if (!link) return;   // no file attached

                            // ── Extract title (col 1) and deadline (col 7) ──
                            const title    = cells[1] ? cells[1].innerText.trim() : '';
                            const deadline = cells[7] ? cells[7].innerText.trim() : '';

                            out.push({
                                href:     link.href,
                                title:    title,
                                deadline: deadline,
                                rowText:  row.innerText.trim(),
                            });
                        });
                        return out;
                    }
                """)

                return [
                    {
                        "url":         r["href"],
                        "title":       r["title"],
                        "deadline":    r["deadline"],
                        "course_name": course_name,
                        "row_text":    r["rowText"],
                    }
                    for r in results
                ]

            if course_options:
                for course in course_options:
                    course_val  = course["value"]
                    course_name = course["text"]
                    log.info(f"  Checking course: {course_name}")
                    try:
                        await page.select_option("#courseId", value=course_val)
                        await page.wait_for_load_state("networkidle", timeout=15_000)
                        links = await _scrape_unsubmitted(course_name)
                        if links:
                            log.info(f"    → {len(links)} UNSUBMITTED assignment(s) found.")
                        downloadable.extend(links)
                    except Exception as ex:
                        log.warning(f"  Could not check course {course_name}: {ex}")
            else:
                links = await _scrape_unsubmitted("General")
                downloadable.extend(links)

            log.info(f"Total unsubmitted assignments found: {len(downloadable)}")

            # ── Step 7: Extract cookies for httpx download ────────────────
            playwright_cookies = await context.cookies()
            httpx_cookies = {c["name"]: c["value"] for c in playwright_cookies}

            # ── Step 8: Download new assignment files & track state ─────────
            for item in downloadable:
                url         = item["url"]
                course_name = item.get("course_name", "General")
                title       = item.get("title") or "Assignment"
                deadline    = item.get("deadline") or "Unknown"
                row_text    = item.get("row_text", "")

                if url in state:
                    log.info(f"Already downloaded, skipping: {title} [{course_name}]")
                    continue

                file_name = _filename_from_download_url(url, title, row_text)
                dest      = DOWNLOAD_DIR / sanitize_filename(course_name) / file_name

                log.info(f"NEW assignment: '{title}' | {course_name} | due {deadline}")
                success = download_file(url, dest, httpx_cookies)

                state[url] = {
                    "title":        title,
                    "deadline":     deadline,
                    "course":       course_name,
                    "downloaded_at": datetime.utcnow().isoformat(),
                    "success":      success,
                    "local_path":   str(dest) if success else None,
                }
                save_state(state)
                new_assignments.append({**state[url], "url": url})

        except PlaywrightTimeout as e:
            log.error(f"Playwright timeout: {e}")
            send_notification(
                "Bahria Watcher - Timeout Error",
                f"Timeout while checking LMS: {e}",
                priority="high",
            )
        except Exception as e:
            log.error(f"Unexpected error: {e}", exc_info=True)
            send_notification(
                "Bahria Watcher - Error",
                f"Error: {e}",
                priority="high",
            )
        finally:
            await browser.close()

    # ── Step 9: Send notifications for new assignments ────────────────────
    if new_assignments:
        # One notification per course listing new assignments
        courses_found = {}
        for item in new_assignments:
            c = item.get("course", "General")
            courses_found.setdefault(c, []).append(item)

        for course, items in courses_found.items():
            successes = [i for i in items if i.get("success")]
            lines = [f"Course: {course}",
                     f"{len(successes)}/{len(items)} file(s) downloaded",
                     ""]
            for i in items[:6]:
                status   = "OK" if i.get("success") else "FAIL"
                title    = i.get("title", "Assignment")
                deadline = i.get("deadline", "?")
                lines.append(f"[{status}] {title}")
                lines.append(f"      Due: {deadline}")
            if len(items) > 6:
                lines.append(f"  ...and {len(items)-6} more")

            send_notification(
                f"New Assignment - {course}",
                "\n".join(lines) + (f"\n\nDownload: {_GH_RUN_URL}" if _GH_RUN_URL else ""),
                priority="high",
            )
    else:
        log.info("No new unsubmitted assignments found this run.")


def _extract_course_name(url: str, text: str) -> str:
    """
    Best-effort extraction of a course name from the URL path or link text.
    Falls back to 'General' if nothing useful is found.
    """
    # Try common patterns like /CS101/ or /course/CS-101/
    patterns = [
        r"/([A-Z]{2,6}[-\s]?\d{3,4}[A-Z]?)/",   # e.g. CS101, EE-302
        r"/courses?/([^/]+)/",
        r"/subject/([^/]+)/",
    ]
    for pat in patterns:
        m = re.search(pat, url, re.IGNORECASE)
        if m:
            return m.group(1).strip()

    # Try to find course-like tokens in link text
    m = re.search(r"\b([A-Z]{2,6}[-\s]?\d{3,4})\b", text)
    if m:
        return m.group(1)

    return "General"


def _filename_from_download_url(url: str, label: str, row_text: str) -> str:
    """
    Extract a meaningful filename from a Download.php?k=<base64> URL.

    The LMS encodes metadata in the 'k' parameter. The base64 value typically
    decodes to a comma-separated string whose last CSV-like field is the
    original filename (e.g. "CCP--AI-07042026-031901pm.pdf").

    Falls back to label text → row text extract → timestamp.
    """
    import base64
    from urllib.parse import urlparse, parse_qs

    try:
        parsed   = urlparse(url)
        qs       = parse_qs(parsed.query)
        k_values = qs.get("k", [])
        if k_values:
            # Add padding just in case
            k_b64   = k_values[0] + "=="
            decoded = base64.b64decode(k_b64).decode("utf-8", errors="ignore")
            # Decoded string often: "id,date,type,flag,filename,domain,..."
            parts = decoded.split(",")
            for part in reversed(parts):
                part = part.strip()
                # Look for a field that ends with a known file extension
                if re.search(r"\.(pdf|docx?|pptx?|xlsx?|zip|rar|7z|txt)$",
                             part, re.IGNORECASE):
                    return sanitize_filename(part)
    except Exception:
        pass

    # Fallback 1: use the link label text
    if label:
        clean = sanitize_filename(label)
        if len(clean) > 3:
            return clean + ".pdf"   # assume PDF if unknown

    # Fallback 2: first file-like token in the row text
    m = re.search(r"[\w\-]+\.(pdf|docx?|pptx?|xlsx?|zip|rar)", row_text,
                  re.IGNORECASE)
    if m:
        return sanitize_filename(m.group(0))

    # Fallback 3: timestamp-based name
    return f"assignment_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.pdf"



# ─────────────────────────────────────────────
#  ENTRY POINT
# ─────────────────────────────────────────────

if __name__ == "__main__":
    log.info("=" * 60)
    log.info("Bahria LMS Watcher starting …")
    log.info(f"Download directory : {DOWNLOAD_DIR}")
    log.info(f"State file         : {STATE_FILE}")
    log.info(f"Log file           : {LOG_FILE}")
    log.info("=" * 60)
    asyncio.run(run_watcher())
    log.info("Run complete.")
